# Generated by Django 3.2.23 on 2024-01-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppKF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Heladeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('producto', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
